DROP DATABASE IF EXISTS gastos_agenda;
CREATE DATABASE IF NOT EXISTS gastos_agenda CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

USE gastos_agenda;

CREATE TABLE IF NOT EXISTS roles(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    activo TINYINT(1) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS usuarios(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(60) NOT NULL,
    apellidos VARCHAR(60) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    contrasena VARCHAR(12) NOT NULL,
    estado ENUM('activo','pendiente','inactivo') NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    rol_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE

)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS tipos(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    tipo VARCHAR(50) NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS gastos(
     id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
     nombre VARCHAR(60) NOT NULL,
     fecha DATE NOT NULL,
     tipo_id INT UNSIGNED NOT NULL,
     usuario_id INT UNSIGNED NOT NULL,
     FOREIGN KEY (tipo_id) REFERENCES tipos(id) ON DELETE CASCADE,
     FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE 
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS detalle_gastos(
     id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
     descripcion VARCHAR(400) NOT NULL,
     cantidad INT UNSIGNED NOT NULL,
     valor INT UNSIGNED NOT NULL,
     gasto_id INT UNSIGNED NOT NULL,
     FOREIGN KEY (gasto_id) REFERENCES gastos(id) ON DELETE CASCADE 
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS notas(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(50) NOT NULL,
    descripcion VARCHAR(400) NOT NULL,
    fecha DATE NOT NULL,
    usuario_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE 
)ENGINE=INNODB;

-- CREA LOS ROLES INICIALES DE ADMINISTRADOR E INVITADO
INSERT INTO roles (nombre,activo) VALUES ('ADMINISTRADOR',1), ('GUEST',1);

-- CREA EL USUARIO ADMINISTRADOR DEL SISTEMA
INSERT INTO usuarios(nombre, apellidos,email, contrasena,estado,rol_id) 
        VALUES('Patricio', 'Contreras', 'patorma@yahoo.com','golotopo','activo',1);

-- ACTUALIZA LA TABLA PARA QUE POR DEFECTO
-- TODOS LOS USUARIOS SEAN INVITADOS
ALTER TABLE usuarios ALTER COLUMN rol_id SET DEFAULT 2;



